version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=YAS
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - local-mysql:/var/lib/mysql
volumes:
  local-mysql: