version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: local-mysql
    environment:
      - MYSQL_DATABASE=yas
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - local-mysql:/var/lib/mysql
    networks:
      - yas-net

volumes:
  local-mysql:

networks:
  yas-net:
    driver: bridge
