version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: local-mysql
    environment:
      - MYSQL_DATABASE=yas
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - local-mysql:/var/lib/mysql
    networks:
      - yas-net

volumes:
  local-mysql:

networks:
  yas-net:
    driver: bridge
