spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./files/

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yas
    username: root
    password: 1234
  servlet:
    multipart:
      location: /Users/duckduck/WorkSpace/yas-back/uploads/
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: yas
    password: 1234


---
spring:
  config:
    activate:
      on-profile: local-docker
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local-mysql/yas
    username: root
    password: 1234
  servlet:
    multipart:
      location: /Users/duckduck/WorkSpace/yas-back/uploads/
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  rabbitmq:
    host: local-mq
    port: 5672
    username: yas
    password: 1234
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yas-mysql/yas
    username: root
    password: 1234

  rabbitmq:
    host: yas-mq
    port: 5672
    username: yas
    password: 1234

---
