spring:
  profiles:
    active: local

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
---
spring:
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/yas-local;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/YAS
    username: root
    password: P@6985w0rd

server:
  port: 8080

---
